#!/usr/bin/env bash
#print To infinity and beyond indefinitely

sudo touch '/var/run/myscript.pid'
sudo chmod 777 '/var/run/myscript.pid'
echo $$ > '/var/run/myscript.pid'

trap  "echo 'I hate the kill command'; sudo rm '/var/run/myscript.pid'; exit;" SIGTERM
trap " sudo rm '/var/run/myscript.pid'; exit;" SIGQUIT 
trap "echo 'Y U no love me?!'; exit;" SIGINT

while ((1));
do
	echo "To infinity and beyond"
	sleep 2
done
